### ISSUE TITLE
sms-tools dependency?

### ISSUE THREAD

**Issue by bam80** [4IceG/luci-app-modemband#6]
Hi, thanks for the project.
Just curious - why `sms-tools` are needed for modem band configuration?

**Comment by 4IceG** [comment]
H @bam80 i, why sms-tool? the answer is simple, for the sake of convenience.

I use the sms-tool to read sms / send ussd codes, it supports at commands sent to the modem, so why not use it? The package has everything I need, so I use it.

**Comment by bam80** [comment]
OK, thanks. Will try to compile then

**Comment by bam80** [comment]
Just for AT commands we could use something from core repo maybe? `socat`, whatever?
But you probably know what you are doing.

**Comment by 4IceG** [comment]
I know that there are other packages that support at commands, the only question is why should I install them additionally? As I wrote above, the sms-tool handles everything I needed.

Compilation may be a problem, sms-tool is not in the OpenWrt repository, but mobile internet users know that there is nothing by default, you want something more.. unfortunately you have to spend some of your time.

I wrote packages for myself because I missed OpenWrt packages that are simple for the user. I have made them available and if someone wants, they can use them. As it is not always possible to use others ipks or write something of your own :).

**Comment by bam80** [comment]
No problem, compilation is on my plan.

As a side-note, I'm searching for possibility of free hosting for personal ASU server, for me and other owrt fellows:
https://forum.openwrt.org/t/online-imagebuilder-and-upgrade-server/18110/543?u=bam80
But it might be not possible on practice, it seem.
